# Generated by Django 4.0.4 on 2022-04-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortHoldings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameFund', models.CharField(max_length=30)),
                ('numHoldings', models.IntegerField(max_length=10)),
                ('institution', models.CharField(max_length=30)),
            ],
        ),
    ]
